# Create an aws encoded demo
# -vars in this file should be passed in
#       ex) --extra-vars "tag_name=your-branch-name"
#
# EXAMPLES
# -Load hosts matching branch name
# $ansible-playbook -i hosts demo_setup.yml --extra-vars "hosts=demo, tag_name=branch_name"

- name: Provision Encoded Demo 
  vars:
    my_hosts: "{{ arg_hosts | default('localhost') }}"
    tag_name: "{{ args_tag_name }}"
  hosts: "{{ my_hosts }}"
  remote_user: root
  roles:
    - provision-encd-demo
